language: android

jdk: oraclejdk8


android:

  components:

    # use the latest revision of Android SDK Tools

    - platform-tools

    - tools



    # The BuildTools version used by your project


    - build-tools-25.0.2



    # The SDK version used to compile your project


    - android-25



    # Additional components

    - extra-android-m2repository

notifications:
    email: false

script: ./gradlew build